hpo_settings:
  data_free: true
  enable_gradnorm: false
  opt_epochs: 5000

training:
  seed: 42

model:
  name: "FourierPINN"
  output_dim: 3
  kernel_init: "glorot_uniform"
  bias_init: 0.0

# === HPO CONFIGURATION ===
hpo_hyperparameters:
  # --- FIXED PARAMETERS ---
  model_width: 512
  model_depth: 4
  ff_dims: 256
  batch_size: 512
  
  loss_weights:
    pde_weight: 1.0
    ic_weight: 1.0
    bc_weight: 1.0
    neg_h_weight: 1.0

  sampling:
    n_points_pde: 65000
    n_points_ic: 10500

  # --- DYNAMIC PARAMETERS ---
  fourier_scale: {min: 5.0, max: 30.0}
  learning_rate: {min: 1e-6, max: 1e-2, log: true}

  sampling:
    n_points_bc_domain: {min: 4000, max: 40000, log: true}

# Fixed Physics/Domain
domain:
  lx: 1200.0
  ly: 100.0
  t_final: 3600.0
physics:
  u_const: 0.29
  n_manning: 0.03
  g: 9.81
  inflow: null

# Validation for No-Building
validation_grid:
  n_points_val: 42000

plotting:
  nx_val: 101
  t_const_val: 1800.0
  y_const_plot: 0
  plot_resolution: 150
device:
  dtype: "float32"
  early_stop_min_epochs: 4000
  early_stop_patience: 3000
numerics:
  eps: 1e-6