hpo_settings:
  data_free: true
  enable_gradnorm: false
  opt_epochs: 5000

training:
  seed: 42

model:
  name: "DGMNetwork"
  output_dim: 3

# === HPO CONFIGURATION ===
hpo_hyperparameters:
  # --- FIXED PARAMETERS ---
  model_depth: 4
  batch_size: 512
  
  loss_weights:
    neg_h_weight: 1.0
    bc_weight: 1.0

  # --- DYNAMIC PARAMETERS ---
  model_width: [128, 256, 512, 1024]
  learning_rate: {min: 1e-6, max: 1e-2, log: true}

  loss_weights:
    pde_weight: {min: 1.0, max: 1000000.0, log: true}
    ic_weight: {min: 0.01, max: 1000.0, log: true}

  sampling:
    n_points_pde: {min: 10000, max: 120000, log: true}
    n_points_ic: {min: 1000, max: 20000, log: true}
    n_points_bc_domain: {min: 4000, max: 40000, log: true}

# Fixed Physics/Domain
domain:
  lx: 1200.0
  ly: 100.0
  t_final: 3600.0
physics:
  u_const: 0.29
  n_manning: 0.03
  g: 9.81
  inflow: null

# Validation for No-Building
validation_grid:
  n_points_val: 42000

plotting:
  nx_val: 101
  t_const_val: 1800.0
  y_const_plot: 0
  plot_resolution: 150
device:
  dtype: "float32"
  early_stop_min_epochs: 4000
  early_stop_patience: 3000
numerics:
  eps: 1e-6