hpo_settings:
  data_free: true
  enable_gradnorm: false
  opt_epochs: 2000

training:
  seed: 42

scenario: "one_building_DEM_zero"

model:
  name: "MLP"
  output_dim: 3

# === HPO CONFIGURATION ===
hpo_hyperparameters:
  # --- FIXED PARAMETERS ---
  model_depth: 4
  model_width: 512
  
  loss_weights:
    neg_h_weight: 1.0
    building_bc_weight: 1.0
    ic_weight: 1.0

  # --- DYNAMIC PARAMETERS ---
  learning_rate: {min: 1e-6, max: 1e-2, log: true}
  batch_size: [256, 512, 1024]

  loss_weights:
    pde_weight: {min: 1.0, max: 1000000.0, log: true}
    bc_weight: {min: 0.01, max: 1000.0, log: true}

  sampling:
    n_points_bc_building: {min: 1000, max: 20000, log: true}
    n_points_bc_domain: {min: 4000, max: 40000, log: true}
    n_points_ic: {min: 1000, max: 20000, log: true}
    n_points_pde: {min: 10000, max: 120000, log: true}

# Fixed Physics/Domain
domain:
  lx: 1200.0
  ly: 100.0
  t_final: 3600.0
building:
  x_min: 325.0
  x_max: 375.0
  y_min: 25.0
  y_max: 75.0
physics:
  u_const: 0.29
  n_manning: 0.03
  g: 9.81
  inflow: null

plotting:
  nx_val: 101
  t_const_val: 1800.0
  y_const_plot: 0
  plot_resolution: 150
device:
  dtype: "float32"
  early_stop_min_epochs: 4000
  early_stop_patience: 3000
numerics:
  eps: 1e-6