hpo_settings:
  data_free: true
  enable_gradnorm: false
  opt_epochs: 2000
training:
  seed: 42
scenario: one_building_DEM_zero
model:
  name: FourierPINN
  output_dim: 3
  kernel_init: glorot_uniform
  bias_init: 0.0
  width: 256
  depth: 4
  ff_dims: 256
  fourier_scale: 10.0
domain:
  lx: 1200.0
  ly: 100.0
  t_final: 3600.0
sampling:
  n_points_pde: 68000
  n_points_ic: 1800
  n_points_bc_domain: 10000
  n_points_bc_building: 4000
building:
  x_min: 325.0
  x_max: 375.0
  y_min: 25.0
  y_max: 75.0
  nx: 20
  ny: 20
  nt: 20
physics:
  u_const: 0.29
  n_manning: 0.03
  inflow: null
  g: 9.81
loss_weights:
  pde_weight: 1.0
  ic_weight: 1.0
  bc_weight: 1.0
  building_bc_weight: 1.0
  neg_h_weight: 1.0
  data_weight: 0.0
gradnorm:
  learning_rate: 0.01
plotting:
  nx_val: 101
  t_const_val: 1800.0
  y_const_plot: 0
  plot_resolution: 150
device:
  dtype: float32
  early_stop_min_epochs: 4000
  early_stop_patience: 3000
numerics:
  eps: 1e-6
train_grid:
  n_points_train: 2000
hpo_hyperparameters:
  sampling:
    n_points_bc_building: 4000
    n_points_ic: 1800
    n_points_pde: 68000
  loss_weights:
    pde_weight: 1.0
    building_bc_weight: 1.0
    bc_weight: 1.0
    neg_h_weight: 1.0
    ic_weight: 1.0
  model_depth: 4.089108910891089
