import numpy as np
import argparse
import os

def convert_bin_to_npy(bin_filepath: str, npy_filepath: str):
    """
    Loads the custom binary file generated by the C++ preprocessor and saves
    it as a NumPy .npy file.
    
    Args:
        bin_filepath (str): The path to the input .bin file.
        npy_filepath (str): The path to save the output .npy file.
    """
    print(f"Reading binary data from: {bin_filepath}")
    
    if not os.path.exists(bin_filepath):
        raise FileNotFoundError(f"Error: The file {bin_filepath} was not found.")
    
    # Read the entire binary file directly into a NumPy array
    # Each row has 6 doubles (float64), so we read as float64 and reshape
    numpy_array = np.fromfile(bin_filepath, dtype=np.float64)
    
    # Reshape to (N, 6) where N is the number of rows
    num_rows = numpy_array.shape[0] // 6
    numpy_array = numpy_array.reshape(num_rows, 6)
    
    # Convert to float32 to save space (if needed)
    numpy_array = numpy_array.astype(np.float32)
    
    print(f"Successfully loaded {numpy_array.shape[0]} rows.")
    
    # Ensure the output directory exists
    output_dir = os.path.dirname(npy_filepath)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        
    # Save the array to the specified .npy file
    np.save(npy_filepath, numpy_array)
    print(f"Array saved to: {npy_filepath} with shape {numpy_array.shape}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Convert custom C++ binary data file to a NumPy .npy file."
    )
    parser.add_argument(
        "input_bin", 
        type=str, 
        help="Path to the input binary (.bin) file generated by the C++ preprocessor."
    )
    parser.add_argument(
        "output_npy", 
        type=str, 
        help="Path for the output NumPy (.npy) file."
    )
    
    args = parser.parse_args()
    
    try:
        convert_bin_to_npy(args.input_bin, args.output_npy)
    except Exception as e:
        print(f"\nAn error occurred: {e}")
